version: "3"
services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poloirab
      POSTGRES_DB: ridesim
    ports:
      - "5432:5432"
